/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { AppSettings, Transaction } from '../types';

export const DEFAULT_SETTINGS: AppSettings = {
  org: {
    name: 'Surau Al-Jannah',
    regNo: 'JAIS/05/01/002/2018',
    kariah: 'Kariah Taman Sri Jannah',
    address: 'Jalan Jannah 1, Taman Sri Jannah, 40000 Shah Alam, Selangor',
    bankName: 'Bank Islam',
    bankAccount: '12029010045678',
  },
  ajk: {
    pengerusi: 'Haji Ahmad Bin Othman',
    bendahari: 'Haji Razali Bin Abdullah',
    setiausaha: 'Encik Zulkifli Bin Mansor',
  },
  openingBalances: {
    total: 15500.0,
    bank: 14200.0,
    cash: 1300.0,
  },
  theme: 'emerald',
  categoriesIn: [
    'Duit Tabung Surau/Masjid',
    'Sumbangan Jumaat',
    'Derma Khas / Infak',
    'Sewa Dewan & Kelengkapan',
    'Yuran Kelas Agama & Kuliah',
    'Wakaf Pembangunan Surau',
    'Sumbangan Anak Yatim & Asnaf',
    'Aktiviti Ramadan & Korban',
    'Lain-lain Penerimaan',
  ],
  categoriesOut: [
    'Bil Elektrik & Air (TNB / SYABAS)',
    'Saguhati Penceramah/Imam',
    'Penyelenggaraan & Pembaikan',
    'Aktiviti Program & Kuliah',
    'Kebajikan Kariah & Asnaf',
    'Barangan Kebersihan & Kelengkapan',
    'Pentadbiran & Alat Tulis',
    'Lain-lain Perbelanjaan',
  ],
};

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    refNo: 'SAJ-202608-0001',
    date: '2026-08-01',
    type: 'IN',
    category: 'Sumbangan Jumaat',
    amount: 1850.0,
    paymentMethod: 'Tunai',
    partyName: 'Jemaah Solat Jumaat',
    notes: 'Kutipan Tabung Jumaat Minggu Pertama Ogos',
    createdAt: Date.now() - 10000000,
  },
  {
    id: 'tx-2',
    refNo: 'SAJ-202608-0002',
    date: '2026-08-03',
    type: 'IN',
    category: 'Wakaf Pembangunan Surau',
    amount: 5000.0,
    paymentMethod: 'Pindahan Bank',
    partyName: 'Hamba Allah (Syarikat Perkasa)',
    notes: 'Sumbangan Wakaf Karpet & Penghawa Dingin',
    createdAt: Date.now() - 9000000,
  },
  {
    id: 'tx-3',
    refNo: 'INV-202608-0001',
    date: '2026-08-04',
    type: 'OUT',
    category: 'Bil Elektrik & Air (TNB / SYABAS)',
    amount: 420.5,
    paymentMethod: 'Pindahan Bank',
    partyName: 'Tenaga Nasional Berhad',
    notes: 'Bayaran Bil Elektrik Dewasa & Ruang Solat',
    createdAt: Date.now() - 8000000,
  },
  {
    id: 'tx-4',
    refNo: 'SAJ-202608-0003',
    date: '2026-08-05',
    type: 'IN',
    category: 'Sumbangan Anak Yatim & Asnaf',
    amount: 1200.0,
    paymentMethod: 'QR Pay',
    partyName: 'Dato Haji Fairuz',
    notes: 'Infak Bantuan Persekolahan Anak Yatim Kariah',
    createdAt: Date.now() - 7000000,
  },
  {
    id: 'tx-5',
    refNo: 'INV-202608-0002',
    date: '2026-08-07',
    type: 'OUT',
    category: 'Saguhati Penceramah/Imam',
    amount: 300.0,
    paymentMethod: 'Tunai',
    partyName: 'Ustaz Azman Shah',
    notes: 'Saguhati Kuliah Maghrib Khas Sira Nabawiyyah',
    createdAt: Date.now() - 6000000,
  },
  {
    id: 'tx-6',
    refNo: 'SAJ-202608-0004',
    date: '2026-08-08',
    type: 'IN',
    category: 'Yuran Kelas Agama & Kuliah',
    amount: 650.0,
    paymentMethod: 'Tunai',
    partyName: 'Peserta Kelas Tajwid & Mengaji',
    notes: 'Kutipan Yuran Bulanan Kelas Tajwid Dewasa',
    createdAt: Date.now() - 5000000,
  },
  {
    id: 'tx-7',
    refNo: 'INV-202608-0003',
    date: '2026-08-10',
    type: 'OUT',
    category: 'Penyelenggaraan & Pembaikan',
    amount: 850.0,
    paymentMethod: 'Pindahan Bank',
    partyName: 'Servis Penghawa Dingin Sri Jannah',
    notes: 'Servis Major 4 Unit Aircond Main Prayer Hall',
    createdAt: Date.now() - 4000000,
  },
  {
    id: 'tx-8',
    refNo: 'INV-202608-0004',
    date: '2026-08-12',
    type: 'OUT',
    category: 'Kebajikan Kariah & Asnaf',
    amount: 500.0,
    paymentMethod: 'Pindahan Bank',
    partyName: 'Keluarga Allahyarham Pak Ismail',
    notes: 'Sumbangan Khairat Kematian & Kebajikan Family',
    createdAt: Date.now() - 2000000,
  },
];
